# Generated by Django 3.0.7 on 2020-06-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodyApp', '0002_auto_20200611_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='orders',
            field=models.TextField(),
        ),
    ]
