# Generated by Django 3.0.7 on 2020-06-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodyApp', '0003_auto_20200611_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(choices=[('organic tomato salad', 'organic tomato salad'), ('Baked broccoli', 'Baked broccoli'), ('Spicy meatballs', 'Spicy meatballs'), ('Eggplant parmigiana', 'Eggplant parmigiana'), ('Grilled Caesar salad, shaved reggiano', 'Grilled Caesar salad, shaved reggiano'), ('Spicy Calamari and beans', 'Spicy Calamari and beans'), ('>Bacon wrapped wild gulf prawns', '>Bacon wrapped wild gulf prawns'), ('Seared ahi tuna fillet*, honey-ginger sauce', 'Seared ahi tuna fillet*, honey-ginger sauce'), ('Grilled Caesar salad, shaved reggiano', 'Grilled Caesar salad, shaved reggiano'), ('Spicy Calamari and beans', 'Spicy Calamari and beans'), ('chettinad chicken', 'chettinad chicken'), ('italian salad', 'italian salad'), ('combo of slad with tuna', 'combo of slad with tuna'), ('fried chicken65', 'fried chicken65'), ('hakka noodels', 'hakka noodels'), ('fruit twist', 'fruit twist'), ('garlic chilly chicken', 'garlic chilly chicken'), ('cabbage salad', 'cabbage salad'), ('grlic bread with white soup', 'grlic bread with white soup'), ('lentils and chicken salad', 'lentils and chicken salad'), ('french toast', 'french toast')], max_length=50),
        ),
    ]
