# Generated by Django 3.0.7 on 2020-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodyApp', '0006_auto_20200612_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='orders',
            field=models.CharField(max_length=2000),
        ),
    ]
