# Generated by Django 3.0.7 on 2020-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodyApp', '0007_auto_20200612_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='orders',
            field=models.TextField(max_length=2000),
        ),
    ]
